FROM balenalib/%%BALENA_MACHINE_NAME%%-node:16-bullseye-run

RUN apt update && apt install -y systemd && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/src/logwatcher
WORKDIR /usr/src/logwatcher

COPY package.json package-lock.json /usr/src/logwatcher/
RUN npm i

COPY tsconfig.json tsconfig.build.json /usr/src/logwatcher/
#dev-cmd-live=npm run dev
COPY lib/ /usr/src/logwatcher/lib/
RUN npm run build

CMD ["npm", "start"]
