import * as Sentry from '@sentry/node';
import _ from 'lodash';
import { isDevelopment, sentryConfig } from './environment';

// tslint:disable-next-line: no-var-requires
const { version } = require('../package.json');
console.log(
	`Initializing sentry to: ${JSON.stringify({
		...sentryConfig,
		release: version,
	})}`,
);

Sentry.init({
	...sentryConfig,
	release: version,
	beforeBreadcrumb(breadcrumb) {
		// Ignore all breadcrumbs not generated by ourselves
		// The available breadcrumb keys are type, category, message, level, timestamp (which many SDKs will set automatically for you), and data,
		return breadcrumb.category !== 'logwatcher' ? null : breadcrumb;
	},
});

export function logSentryEvent(event: Sentry.Event) {
	if (isDevelopment) {
		// console.debug('Sending Sentry Event:\n' + JSON.stringify(event, null, 4));
	}

	Sentry.captureEvent(event);
}
